### ISSUE TITLE
Model ID?

### ISSUE THREAD

**Issue by Th3M3** [bbqkees/EMS-Wiki#1]
Hi there,

I also started a [EMS+ wiki for my Buderus GB125](https://github.com/Th3M3/buderus_ems-wiki) (in german).

In cyclic telegrams of type `bf` I have values in byte 6 I think it is the model identifier you mention in the EMS bus devices documentation.

My [boiler/MC110](https://github.com/Th3M3/buderus_ems-wiki/blob/master/Quelle_08.md#typ-0xbf-ubaerrormessage) has value `85` -> 133 in decimal
My [RC310](https://github.com/Th3M3/buderus_ems-wiki/blob/master/Quelle_10.md#typ-0xbf-rcerrormessage) has value `9e`-> 158 in decimal
My [MM50](https://github.com/Th3M3/buderus_ems-wiki/blob/master/Quelle_21.md#typ-0xbf-mmerrormessage) has value `9f` -> 159 in decimal

Can you tell somthing about in wich telegrams you see the model identifier?

**Comment by bbqkees** [comment]
Hi,
Please have a look at https://github.com/proddy/EMS-ESP
Thats where I got all the ID's from. 
Maybe you should open an issue over there so he can add the identifiers to the list of known devices.
