### ISSUE TITLE
EMS2 - what is meant exactly?

### ISSUE THREAD

**Issue by vampywiz17** [bbqkees/EMS-Wiki#2]
Hello there!

My question is the "EMS2" is different name of EMS+ and HT3 or it is a different protocol?

Because we want to use Tado thermostat and the documentaiton say that is support EMS+ and HT (3 maybe, because it use 2 wire) but the live support say that it NOT support EMS2.

**Comment by bbqkees** [comment]
I'm not completely sure but although the bus has the same electrical specification the protocol on the bus itself is (a bit) different for each version of each Bosch brand.
Which boiler do you have?
